[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "my-toolbox"
version = "0.1.0"
description = "A collection of personal tools"
readme = "README.md"
requires-python = ">=3.7"
license = {text = "MIT"}

[project.scripts]
whousesgpu = "my_toolbox.utils.whousesgpu:main"

[tool.setuptools.packages.find]
where = ["src"]
include = ["my_toolbox*"]

# pip install git+https://github.com/hnyls2002/my-toolbox.git
